=== Ajaybezawada/Yummy-wheel/XML/order_type.dtd
<!ELEMENT orders (order+)>
<!ELEMENT order (orderID, cname, phone, address, date, products,amount)>
<!ELEMENT items (item+)>
<!ELEMENT item (item_name, quantity)>
<!ELEMENT item_name (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT orderID (#PCDATA)>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT amount (#PCDATA)>

=== Ajaybezawada/Yummy-wheel/XML/orders.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE orders SYSTEM "order_type.dtd">
<orders>
    <order>
        <orderID>101</orderID>
        <cname>AJ</cname>
        <phone>9493248889</phone>
        <address>Vijayawada Krishna</address>
        <date>25/08/2022</date>
        <items>
            <item>
                <item_name>Pizza</item_name>
                <quantity>1</quantity>
            </item>
            <item>
                <item_name>Burger</item_name>
                <quantity>1</quantity>
            </item>
        </items>
        <amount>450</amount>
    </order>
</orders>
